### ISSUE TITLE
Set up GitHub Actions for Tests and Coverage

### ISSUE THREAD

**Issue by luiarthur** [lanl/PRISM#1]
Making a note here that eventually we can put some simple tests in `tests/`.

We can set up GitHub Actions to automatically run tests and get coverage reports.

I'm happy to do that when we get to that point.

**Comment by mikegros** [comment]
Sounds good. I have some substantial updates to the HSVGP functionality that I've been negligent about pushing up here. I need to go back through and make sure it's in good enough shape to share out. After I do so and then maybe it would be worth touching base about that.

**Comment by luiarthur** [comment]
Resolved by #2.
